### ISSUE TITLE
哈喽，能补充一些文档吗

### ISSUE THREAD

**Issue by xubillde** [chong2vv/yd-general-ios-app#1]

**Comment by xubillde** [comment]
1.建议YDDB使用MMKV来存。
理由：字段变更需要考虑sql问题。
2.YDAppCheckUpdateService的appid可以放到YDConfig

**Comment by chong2vv** [comment]
之前公司事情太多了就一直没倒出时间弄这个，这段时间会重新优化一下

**Comment by chong2vv** [comment]
已经去掉YDDB的依赖，统一放到了YDLog库，方便实际项目需要上传服务端用来远程查看排查问题

**Comment by xubillde** [comment]
ok

**Comment by chong2vv** [comment]
YDDB这个如果自己使用用不到的话可以去除掉，这个主要是为了有的项目可能自己要做伪即时通讯这种或者类似缓存加载这种的，这种需求的话MMKV的限制就太大了，具体还是看你的实际项目需求，单纯的存用户信息的话数据库的确开销太大了
